name: Upload Python Package to PyPI

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        pip install twine python-semantic-release

    - name: Semantic Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        semantic-release version 
        python setup.py sdist bdist_wheel
        
        if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
          semantic-release publish 
          twine upload dist/* --verbose
        elif [[ ${{ github.ref }} == 'refs/heads/develop' ]]; then
          export TWINE_PASSWORD=${{ secrets.TEST_PYPI_PASSWORD }};
          twine upload --repository testpypi dist/* --verbose 
        fi