name: Run Tests with Pytest

on:
  push:
    branches:
      - '*'

jobs:
  unit-tests-pytest:
    name: Run unit tests with pytest
    runs-on: ubuntu-latest
    steps:
      - name: Install system level libraries
        run: |
          sudo apt-get update
          sudo apt-get -y install libpq-dev gcc

      - name: Checkout code from remote origin.
        uses: actions/checkout@v2

      - name: Add project root to PYTHONPATH
        run: |
          import os
          import sys
          sys.path.append(os.path.abspath('.'))
        shell: python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print current working directory
        run: | 
          pwd
          ls -lart

      - name: Run tests
        run: |
          pytest tests/
        env:
          PYTHONPATH: ${{ github.workspace }}