name: Run Tests with Pytest

on:
  push:
    branches:
      - '*'

jobs:
  unit-tests-pytest:
    name: Run unit tests with pytest
    runs-on: ubuntu-latest
    steps:
      - name: Change to root directory
        run: cd $GITHUB_WORKSPACE

      - name: Install system level libraries
        run: |
          sudo apt-get update
          sudo apt-get -y install libpq-dev gcc

      - name: Checkout code from remote origin.
        uses: actions/checkout@v2

      - name: Setup python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Add project root to Python Path
        run: |
          ls -lart 
          export PYTHONPATH="$GITHUB_WORKSPACE/algotrade"
          echo $PYTHONPATH

      - name: Install & Run pytest
        run: |
          dir 
          echo $PYTHONPATH
          python -m pip install -r requirements.txt
          pytest tests/
