name: Run Tests with Pytest

on:
  push:
    branches:
      - '*'
#  workflow_run:
#    workflows: ["build-image.yml"]
#    types:
#      - completed

jobs:
  unit-tests-pytest:
    name: Run unit tests with pytest
    runs-on: ubuntu-latest
    steps:
      - name: Install system level libraries
        run: |
          sudo apt-get update
          sudo apt-get -y install libpq-dev gcc

      - name: Checkout code from remote origin.
        uses: actions/checkout@v2

      - name: Setup python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install & Run pytest
        run: |
          python -m pip install -r requirements.txt
          pytest tests/
